packaging_format = 2

id = "synapse-admin"
name = "Synapse Admin"
description.en = "Admin UI for Synapse"
description.fr = "Admin UI pour Synapse"

version = "0.8.7~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
code = "https://github.com/Awesome-Technologies/synapse-admin"

[integration]
yunohost = ">= 11.1.17"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.synapse_app]
    ask.en = "Input the Synapse app ID you wish to connect to."
    ask.fr = "Entrez l'ID de l'app Synapse à laquelle vous souhaitez vous connecter."
    help.en = "Leave the default value if you have only one Synapse server installed."
    help.fr = "Laissez la valeur par défaut si vous n'avez installé qu'un seul serveur Synapse."
    type = "string"
    default = "synapse"

    [install.init_main_permission]
    help.en = "If enabled, Synapse Admin will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Synapse Admin sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/Awesome-Technologies/synapse-admin/releases/download/0.8.7/synapse-admin-0.8.7-dirty.tar.gz"
    sha256 = "3f74cbfec0a3b14b5684d1bded4816a7946d2e9b88b7186767189c14811224e9"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    
    [[resources.apt.extras]]
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
