#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "synapse-admin"
name = "Synapse Admin"
description.en = "Admin UI for Synapse"
description.fr = "Admin UI pour Synapse"

version = "0.10.3-etke33~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
code = "https://github.com/etkecc/synapse-admin"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = true

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.synapse_app]
    ask.en = "Input the Synapse app ID you wish to connect to."
    ask.fr = "Entrez l'ID de l'app Synapse à laquelle vous souhaitez vous connecter."
    help.en = "Leave the default value if you have only one Synapse server installed."
    help.fr = "Laissez la valeur par défaut si vous n'avez installé qu'un seul serveur Synapse."
    type = "app"
    default = "synapse"

    [install.init_main_permission]
    help.en = "If enabled, Synapse Admin will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Synapse Admin sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/etkecc/synapse-admin/releases/download/v0.10.3-etke33/synapse-admin.tar.gz"
    sha256 = "ca1ba8d3b149b05db1723f763b908d9ee36a219f922c6327ef62b785826ca680"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "synapse-admin-.*.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
