test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.multi"]

    preinstall = """
    sudo yunohost tools update apps
	sudo yunohost app install https://github.com/YunoHost-Apps/synapse_ynh/tree/823f98a8cbe108ad4cc0e38e280a83401dca2b9f -a "domain=sub.domain.tld&server_name=$server_name&is_free_registration=$is_free_registration&jitsi_server=$jitsi_server" --force
    """

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.synapse_app = "synapse"
    args.synapse_domain="sub.domain.tld"
		