#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]
    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.allowed_matrix_server = "example.com"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.84016fce4cf2ca8b209ecc669f826a128013c15f.name = "Upgrade from 0.10.3.37~ynh1"
    test_upgrade_from.03ea8c9.name = "Before adding sub-path support"
    test_upgrade_from.d29d3e0aa90f61666a543310662f9efbbef10eca.name = "Before cleaning install parameters"
