#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]
    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.allowed_matrix_servers = "example.com"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.f3575065711ba4bb5b17f4ecf11ef1c4c5c441c5.name = "Before introducting new parameter allowed_matrix_servers"

    # -------------------------------
    # Curl tests to validate that the app works
    # -------------------------------
    [default.curl_tests]
    root.path = "/"
    root.expect_title = "Synapse Admin"
    root.expect_content = 'You need to enable JavaScript to run this app\.'

    config.path = "/config.json"
    config.expect_content = '\{[\n\s]*"restrictBaseUrl"'
