#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    preinstall = """
    sudo yunohost tools update apps
    sudo yunohost app install \
        https://github.com/YunoHost-Apps/synapse_ynh/tree/1c36215f03e5bc1b4c22ec42f93e6188f73a9f36 \
        -a "domain=sub.domain.tld&server_name=$server_name&is_free_registration=$is_free_registration&jitsi_server=$jitsi_server" \
        --force
    """

    test_upgrade_from.4eaa242f.name = "Upgrade from 0.8.5~ynh5 and remove app build"
