#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# GET SYNAPSE SETTINGS
#=================================================
ynh_script_progression "Getting settings from Synapse..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir=$install_dir

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx
_add_synapse_endpoint_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
