#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if ynh_app_upgrading_from_version_before_or_equal_to 0.8.3~ynh2; then
    ynh_die "Upgrade from version 0.8.3 is not possible. You must uninstall and reinstall Synapse-admin package manually"
fi

# If synapse_app doesn't exist, create it and assume it is `synapse`
ynh_app_setting_set_default --key=synapse_app --value="synapse"

# Delete service and nodejs dependencies
if ynh_app_upgrading_from_version_before 0.8.7~ynh1; then
    yunohost service remove $app
    ynh_config_remove_systemd

    ynh_nodejs_remove
    ynh_config_remove_logrotate

    ynh_app_setting_delete --key=synapse_port
    ynh_app_setting_delete --key=port
fi

if ynh_app_upgrading_from_version_before 0.8.7~ynh3; then
    ynh_app_setting_delete --key=synapse_domain
    ynh_app_setting_delete --key=synapse_port
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx
_add_synapse_endpoint_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
